Name:           ros-indigo-moveit-planning-helper
Version:        1.0.4
Release:        0%{?dist}
Summary:        ROS moveit_planning_helper package

Group:          Development/Libraries
License:        GPLv3
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-actionlib
Requires:       ros-indigo-actionlib-msgs
Requires:       ros-indigo-convenience-ros-functions
Requires:       ros-indigo-eigen-conversions
Requires:       ros-indigo-manipulation-msgs
Requires:       ros-indigo-moveit-ros-planning-interface
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-shape-tools
Requires:       ros-indigo-tf
Requires:       ros-indigo-trajectory-msgs
BuildRequires:  ros-indigo-actionlib
BuildRequires:  ros-indigo-actionlib-msgs
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-convenience-ros-functions
BuildRequires:  ros-indigo-eigen-conversions
BuildRequires:  ros-indigo-manipulation-msgs
BuildRequires:  ros-indigo-moveit-ros-planning-interface
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-shape-tools
BuildRequires:  ros-indigo-tf
BuildRequires:  ros-indigo-trajectory-msgs

%description
A test package to plan and execute a joint trajectory. This package is only in
here for testing during development. At some stage, this will move to a new
package with all motion-plan related functionalities, e.g.
joint_trajectory_planning and joint_trajectory_execution.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Tue Feb 06 2018 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 1.0.4-0
- Autogenerated by Bloom

* Wed Jan 10 2018 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 1.0.2-0
- Autogenerated by Bloom

* Sat Jan 06 2018 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 1.0.1-0
- Autogenerated by Bloom

* Thu Jun 09 2016 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 1.0.0-0
- Autogenerated by Bloom

