Name:           ros-indigo-moveit-object-handling
Version:        1.0.2
Release:        0%{?dist}
Summary:        ROS moveit_object_handling package

Group:          Development/Libraries
License:        GPLv3
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-convenience-ros-functions
Requires:       ros-indigo-eigen-conversions
Requires:       ros-indigo-gazebo-state-plugins
Requires:       ros-indigo-gazebo-test-tools
Requires:       ros-indigo-geometry-msgs
Requires:       ros-indigo-moveit-msgs
Requires:       ros-indigo-object-msgs
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-sensor-msgs
Requires:       ros-indigo-shape-msgs
Requires:       ros-indigo-shape-tools
Requires:       ros-indigo-std-msgs
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-convenience-ros-functions
BuildRequires:  ros-indigo-eigen-conversions
BuildRequires:  ros-indigo-gazebo-state-plugins
BuildRequires:  ros-indigo-gazebo-test-tools
BuildRequires:  ros-indigo-geometry-msgs
BuildRequires:  ros-indigo-message-generation
BuildRequires:  ros-indigo-moveit-msgs
BuildRequires:  ros-indigo-object-msgs
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-sensor-msgs
BuildRequires:  ros-indigo-shape-msgs
BuildRequires:  ros-indigo-shape-tools
BuildRequires:  ros-indigo-std-msgs

%description
Package which helps generate the MoveIt! moveit_msgs/CollisionObject messages
for existing objects in the scene, described by object_msgs/Object. Also
provides helper classes for MoveIt! in relation to objects.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Wed Jan 10 2018 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 1.0.2-0
- Autogenerated by Bloom

* Sat Jan 06 2018 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 1.0.1-0
- Autogenerated by Bloom

* Thu Jun 09 2016 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 1.0.0-0
- Autogenerated by Bloom

